testdouble/testdouble.js

lib/matchers.coffee, test/helper.coffee, test/lib/matchers-test.coffee, test/lib/verify-test.coffee
resolves #9 
This seems to cover all the obvious cases I can think of.
=> add more matchers

lib/explain.coffee, lib/store/calls.coffee, lib/store/stubbings.coffee, lib/stringify-args.coffee, lib/when.coffee, test/lib/explain-test.coffee, test/lib/when-test.coffee
=> sequential stubbing

lib/create.coffee, lib/explain.coffee, lib/verify.coffee, test/helper.coffee, test/lib/explain-test.coffee, test/lib/verify-test.coffee
=> Allow naming test doubles for better output

README.md
I love me some syntax highlights ✨
=> add some more syntax highlighting to README

lib/create.coffee, lib/store/calls.coffee, lib/store/stubbings.coffee, lib/verify.coffee, test/lib/verify-test.coffee, test/lib/when-test.coffee
=> Add a `times` option

README.md
Replace blurry png with crispy svg.
=> Use svg build badge

lib/replace.browser.coffee, lib/replace.coffee, package.json
Swaps the replace function (in browser) for a function that just throws an
error. No separate node/browser test designations yet. That'll be a separate PR
=> Swap .replace with browser-specific function

package.json
=> Add webpack specific metadata to package.json

docs/B-frequently-asked-questions.md, src/args-match.coffee, src/verify.coffee, test/src/args-match-test.coffee, test/src/verify-test.coffee
=> Warn verifications of exact stubbings

src/object.coffee
Fixes #112. Tested with Node 6.2.1.
=> Generate test double name for a Proxy test double

package.json, src/stringify/anything.coffee
switching us back to [stringify-object](https://github.com/yeoman/stringify-object) now that my fork's changes were merged
=> Use stringify-object now that my change is merged

src/explain.coffee, test/src/explain-test.coffee
Fixes #126.
Feedback very welcome!
=> explain plan better in stubbing description

package.json, src/args-match.coffee, src/config.coffee, src/explain.coffee, src/function.coffee, src/matchers/callback.coffee, src/matchers/create.coffee, src/matchers/index.coffee, src/object.coffee, src/replace/imitate.coffee, src/replace/index.coffee, src/replace/is-constructor.coffee, src/replace/property.coffee, src/replace/wrap-with-constructor.coffee, src/reset.coffee, src/store/calls.coffee, src/store/index.coffee, src/store/stubbings.coffee, src/stringify/anything.coffee, src/stringify/arguments.coffee, src/verify.coffee, src/when.coffee
=> Upgrade to lodash 4.15.0

src/verify.coffee, test/src/verify-test.coffee
=> Gives better hint when verification fails while ignoring extra args

src/object.coffee
Including a "did you mean" line. Shiny.
=> Improve the error message when using Proxy incorrectly.

index.d.ts
=> Add typings for config function

index.d.ts, test/src/typescript/test.ts
Ran `test:typescript` npm script before committing.
=> Fix #236; Add another overload and its test

docs/5-stubbing-results.md
"were" for subjunctive mood (hypotheticals)
=> grammar tweak

docs/4-creating-test-doubles.md
```diff
- We recommend on landing on one consistent style
+ We recommend landing on one consistent style
```
=> Remove extra word

src/object.js
=> Erroring on undefined for td.object

.github/issue_template.md
Just an idea/draft.
1.  Would an issue template make us more effective at handling issues?
1.  Is _this_ issue template a step in the right direction?
=> First draft of issue template

examples/webpack/testem.json
if we can get it going will fixes #334
=> fix webpack example project

README.md, regression/src/testdouble-test.coffee, src/imitate/initialize-names.js, src/index.js, src/replace/module.js, test/unit/imitate/initialize-names.test.js, test/unit/index.test.js
Doing this in support of a testdouble-jest module
=> Publicize td.imitate()

src/matchers/is-matcher.js, src/object/proxy.ts, src/stringify/anything.js, test/safe/verify.test.js, test/safe/when.test.js
=> Fix .verify() and .when() when using testdouble objects as arguments

index.d.ts, test/safe/typescript-typings.test.ts
=> update td.when types

src/object/proxy.ts, src/verify.js, test/safe/object.test.js, test/safe/verify.test.js
Update references to `master` to instead refer to `main`, since the default branch has now been renamed.
I'm opening this as a PR specifically because it changes actual code and want to make it visible. Given actual code changes, should this be released to npm too?
=> master -> main

index.d.ts
They should support sequential return values.
=> Fix thenReject and thenThrow types
