testdouble/testdouble.js

lib/create.coffee, test/lib/verify-test.coffee
This is a big enough feature to warrant a more obvious test location
but given that we're testing create through when & verify, and
only verify() can see the name of each test double (which is 
part of the work here), i just plopped it there.
Resolves #2
=> Test prototype-based create()

package.json, testem.js
Presently, only the node launcher is configured. Browser testing still WIP
`npm start` runs testem (this would be the tdd dev flow)
`npm test` runs mocha (defaulting to spec output, but can be configured via .npmrc) and exits
`npm run test:debug` runs mocha and breaks into debug mode
=> Configure Testem

package.json
=> Browserify

testem.js
src_files are served *and* watched. but the src_files are generated JS
files, so each test run generates new js files, which are being watched
so it triggers another build, ad infinitum
testem supports serve_files which are served but not watched (which
requires watch_files to be specified separately)
=> don't watch generated files

lib/args-match.coffee, test/lib/verify-test.coffee
Really obvious & stupid miss found by @mweitzel
Resolves #33
=> Start checking arity on arg comparisons

lib/matchers/captor.coffee, lib/matchers/index.coffee, test/lib/captor-test.coffee
Implements argument captors, they're a matcher like anything else.
Resolves #35
=> Arg captors

lib/args-match.coffee, lib/store/calls.coffee, lib/store/stubbings.coffee, lib/verify.coffee, lib/when.coffee, test/lib/verify-test.coffee, test/lib/when-test.coffee
Sometimes we don't care about the args when we stub or verify. Sometimes we only care about the first `n` args. In those cases, you can use the `ignoreExtraArgs` option. It's pretty neato.
Resolves #36
=> Add an option to ignore additional args

docs/5-stubbing-results.md, package.json, src/matchers/callback.coffee, src/store/stubbings.coffee, src/testdouble.coffee, src/when.coffee, test/browser-helper.coffee, test/general-helper.coffee, test/lib/callback-test.coffee, test/lib/captor-test.coffee, test/lib/explain-test.coffee, test/lib/matchers-test.coffee, test/lib/object-test.coffee, test/lib/replace-test.coffee, test/lib/testdouble-test.coffee, test/lib/verify-test.coffee, test/lib/when-test.coffee, test/node-helper.coffee, testem.js
=> Implement callback stubbing APIs

src/explain.coffee, src/function.coffee, src/store/index.coffee, test/lib/explain-test.coffee
* Allow td lookups that don't create an entry in the store
This was an oversight to begin with
* td.explain() returns isTestDouble for easy checks of whether
you just passed it a testDouble or not and gives a description
to match
=> td.explain tells you if you passed it a test double

docs/5-stubbing-results.md
Both `thenDo` and `thenThrow` have been implemented and documented. However there was a reference to them being unimplemented earlier in the file. Changed that to reference their description later in the file.
=> doc: thenDo and thenThrow are no longer unimplemented.

src/replace/property.coffee, test/src/replace/index-test.coffee
=> replace: Use object[property] to check if property exists

CHANGELOG.md, package.json
Uses the [github_changelog_generator](https://github.com/skywinder/github-changelog-generator) to create a changelog every time `npm version [segment]` is run.
Fixes #97
=> Generate a changelog whenever we pubish

src/matchers/index.coffee, test/src/matchers-test.coffee
Previously, `td.matchers.contains()` behavior for array arguments made no sense and would only work for strings and plain objects, incidentally. The error that was logged should have been targeted at `actualArg`, but it's not fair to log the error based on `actualArg` since it'll cause verifications to appear to fail even if one does satisfy
Thanks a lot to @focusaurus for his patience!
Fixes #102
=> Fix contains() behavior for arrays

docs/A-plugins.md
I added [testdouble-timers](https://github.com/kuy/testdouble-timers) to the docs. But I feel that it doesn't fit with the description because `testdouble-timers` doesn't bridge the `verify()` method. Please move my link if you also feel that and separate the section 😄
=> Add testdouble-timers as plugin to docs

src/store/calls.coffee, test/src/when-test.coffee
Found this working on a characterization test for @schoonology -- sometimes when test doubles return test doubles (Which they should not do!), nesting stubs for the sake of locality/terseness is preferable over lots of extra variables. It's surprising when this does not work.
Fixes #117
=> Allow nested stubbing configuration

docs/4-creating-test-doubles.md
As for Oct 22nd 2016, proxies are supported in recent versions of all major browsers and in node 6.x. Safari 10 joined that club a couple of days ago.
=> Remove warning of implementations of ES2015 proxy

src/matchers/captor.coffee, test/src/captor-test.coffee
Allowing multiple invocations to a captor which will store all captured values in .values. .value still remain for backwards compatibility, and will always contain the last invoked capture value.
=> Allow for multiple captor invocations

index.d.ts, package.json, test/src/typescript/test.ts, test/src/typescript/tsconfig.json
Resolves https://github.com/testdouble/testdouble.js/issues/167
I'm not sure about how to test it properly in your configuration, but it looks like my variant would be ok.
I've added feature from new ts 2.1, but it's only needed for one case `td.object(['a', 'b'])`. Also not sure what to add into README.md.
=> Typings for typescript

index.d.ts
This PR changes the TypeScript type definition for `td.replace()` to return `any` instead of `void`.
Per the [documentation](https://github.com/testdouble/testdouble.js/blob/5cbd55529d6b4cc1d28d27253c03ad3221b691f1/docs/7-replacing-dependencies.md#tdreplace-api):
> ### td.replace(object, propertyName, [manualReplacement])
> [...]
> `td.replace` typically returns the fake thing it sets on `object`, with the
> exception of constructor function properties. In that case, it will return a
> plain object of test double functions to the test, but set `object[propertyName]`
> to a constructor function that delegates to those test double functions only
> after it's been instantiated with `new`.
and
> ### td.replace(relativePathToModule, [manualReplacement])
> [...]
> Once defined, it will return a …
=> Align TS replace() signuatrue return with implementaiton

index.d.ts
This PR:
1. Changes all type aliases to multi-property objects to interfaces.
- This is a backwards compatible change; it will not affect compilation.
- Interfaces allow [declaration merging], while type aliases do not. So, if the type definitions fall behind the implementation (for instance, missing the `captor()` function), downstream users can declaration-merge in a patch to keep going until the official type def is updated.
1. Adds `td.matchers.captor()` to the type definitions.
[declaration merging]: https://www.typescriptlang.org/docs/handbook/declaration-merging.html
=> Captor typings

docs/5-stubbing-results.md, src/matchers/index.coffee, src/util/lodash-wrap.coffee, test/src/matchers-test.coffee
This is my initial stab at adding RegExp support to the contains matcher. Let me know if/what kind of [other] edge cases you'd like me to cover :)
Also if this is not considered to be a good idea, I'd love to know why that decision was made. If I understand the `argThat` matcher correctly, this is just an alias that allows users to inline their assertion in the test which makes them read better IMHO leading to easier maintainability.
=> feat: contains allows for regexps against strings

src/util/lodash-wrap.coffee, src/verify.coffee, test/src/verify-test.coffee
Adds a section to the unsatisfied verification message to describe
calls that match the verification. This section is displayed when the testdouble is
configured with a `times` that is greater than the number of matching
calls.
Example:
Wanted:
- called with `(isA(Number))` 4 times.
3 calls that satisfied this verification:
- called 1 time with `(1)`
- called 2 times with `(2)`
All calls of the test double, in order were:
- called with `(1)`.
- called with `(2)`.
- called with `(2)`.
- called with `("x")`.
This closes: Better verification messages #161
completed with @tinney
=> Creates Better Verification Message

src/verify.coffee, test/src/verify-test.coffee
After a verification is made, a warning can be produced to signal that
the verification call matches a stub on the same testdouble. This
behavior is improved to test the verification against the stubbing using
the stubs matchers and config options.
This closes: stub also verified warning when using ignoreExtraArgs #181
completed with @tinney
=> Improves warning when verifying a stub

package.json, src/args-match.coffee, src/matchers/create.coffee, src/stringify/anything.coffee, src/util/lodash-wrap.js, test/src/stringify/anything-test.coffee, test/src/verify-test.coffee, test/src/when-test.coffee, yarn.lock
=> Support deep matchers

README.md, docs/5-stubbing-results.md, src/store/stubbings.coffee, src/util/lodash-wrap.js, test/src/callback-test.coffee
Continues the work Sam started, adding:
Resolves #198, #106
=> Async callbacks

src/function.js, src/store/stubbings.js, test/src/when-test.coffee
This is required for some APIs where we might not have access to, but require (e.g. in fluent chains) the instance the function is being called on ahead of time.
You can be double-sure this works because I implemented it in both CoffeeScript and JavaScript, as #206 was merged while I was writing it 😉
=> Preserve function context when calling thenDo

test/src/replace/index-test.coffee
I think we discussed this case a long time ago, but this test fails when trying to `td.reset` a quibble-replaced module: the test double is still there.
=> Add failing test for resetting replaced modules.

docs/7-replacing-dependencies.md, docs/B-frequently-asked-questions.md, examples/node/lib/elastic-thing.js, examples/node/lib/numbers-only.js, examples/node/package.json, examples/node/test/lib/elastic-thing-test.js, examples/node/test/lib/numbers-only-test.js, examples/node/yarn.lock, package.json, src/replace/module.js, test/fixtures/car.coffee, test/src/replace/index-test.coffee, yarn.lock
Requires us to resolve the path from the perspective of CWD for the 
first time, and adds @substack's resolve package as a dependency.
Hopefully that is very fast when a path starts with `.` and doesn't
slow down existing tests much!
Fixes #51
=> Add support for third party modules

src/config.js, src/constructor.js, test/src/config-test.js, test/src/constructor-test.coffee
**This is a breaking change**
I made a mistake in td 2.0 and it took too long to catch. Mea culpa. I feel bad.
I've decided after fighting various babel shenanigans to give up on trying to create test double constructors that will pass instanceof checks. The reality is that the ES Class spec buttons up any cuteness I'd been able to previously get away with, namely
1. There's no way to pass an `instanceof` check of a class without extending it
2. There's no way to extend a class without invoking the super constructor upon instantiation (the sole alternative is to instantiate it manually and return that from the sub constructor, but for our purposes that has the same downside—production code of a dependency getting executed by a unit test).
3. We have since learned that when …
=> Stop extending types when replacing constructors

package.json, script/repl, src/callback.js, src/function/create.js, src/function/imitate.js, src/function/index.js, src/function/remember.js, src/index.js, src/store/stubbings.js, src/when.js, src/wrap/lodash.js, test/browser-helper.js, test/node-helper.coffee, test/src/testdouble-test.coffee, unit/function/index.test.js, unit/helper.js, unit/index.test.js, yarn.lock
I've never been happy with this library's "unit" test suite because it's
too extrinsic, poking at things only through the top-level exposed td.*
API methods. This is a fine strategy for smaller libraries, but on
larger libraries like this one, it encourages large units and extract
refactors in the src code tend to be more arbitrary and less symmetrical
to the test files, which increases onboarding time for others and adds
some indirection when trying to find the spot in the code that a test is
specifying.
This was done for two reasons at the time, both of which I now regret:
1. testdouble.js didn't exist yet, so doing my brand of Discovery
Testing would be hard.
2. I didn't trust Browserify to work, so I went out of my way at first
to test the built Browserified lib extrinsically in a …
=> Test testdouble.js with testdouble.js!

package.json
lodash@4.17.0 added support for async functions to `_.isFunction`, which allows testdouble.js to properly detect (mockable) functions on objects.
I believe this should fix #284.
=> Upgrade lodash (and support async functions)

docs/8-custom-matchers.md, regression/src/captor-test.coffee, src/matchers/builtin/captor.js, src/matchers/create.js, src/matchers/notify-after-satisfaction.js, src/satisfy/index.js, src/store/stubbings.js, src/verify.js, test/unit/satisfy/index.test.js
@jamestalmage made a good catch in #308 that captors could be used with `td.when` but it was undocumented and it would also capture values when the rest of the rehearsal did not match the actual args. This was effectively a requirements miss, but because our goal is to have `td.when` and `td.verify` to behave as symmetrically as possible, it's something we needed to fix.
James implemented a fix in #310, but I had three quibbles with it: (a) it broadened awareness of "capturing" to matchers themselves, even though captors are a one-off subset, (b) it expanded the private namespace claimed by matchers with `__capture`, and (c) it didn't verify that an argument was a matcher before invoking `__capture`.
Fixes #310 
Fixes #308
=> Ensure captors only fire when invocation satisfies when/verify

regression/src/matchers-test.coffee, src/matchers/builtin/contains.js
This allows us to do things like:
```javascript
brew({nested: {nestedString: 'abc', irrelevant: true}, irrelevantHere: 'alsoTrue'})
td.verify(brew(td.matchers.contains({irrelevantHere: td.matchers.isA(String)})))
td.verify(brew(td.matchers.contains(
{nested: td.matchers.contains({nestedString: td.matchers.isA(String)})}
)));
```
Before, the tests I added were failing (basically, you weren't able to mix matcher.contains with other matchers (including another matcher.contains as showed above)
=> allow using matchers inside contains

regression/src/constructor-test.coffee, regression/src/object-test.coffee, src/constructor.js, src/imitate/create-imitation.js, src/object.js, test/unit/imitate/create-imitation.test.js
Apparently (https://github.com/nodejs/node/issues/927#issuecomment-75623216),
Symbols cannot be implicitly coerced to string.
Template stringification leverages implicit coercion, so we must
stringify propKey before sending it to the template.
Options for explicitly stringifying:
- `String(propKey)`
- `String.prototype.toString(propKey)`
Differences:
```
> String(undefined)
'undefined'
> String.prototype.toString(undefined)
''
```
In this case, `propKey` represents the key for the stubbed function. If
the key is `undefined`, it would be implicitly coerced to `"undefined"`
as the property key. So `String()` is the explicit converstion we want.
fixes #300 and perhaps maybe fixes #124 ?
=> Symbols must be stringified explicitly

docs/3-getting-started.md
Since `td.object` does not support a constructor function as parameter anymore, the docs became outdated.
Issue: #329
=> Updated Getting Started to match td.object()'s changes

package-lock.json, package.json
`npm install` fails on Windows, because `rm -rf` doesn't exist. When that issue is resolved, `dist/testdouble.js` fails to generated, because Windows can't parse `$npm_package_config_build_file`.
`npm install` works on Windws.
[x] Replaced `rm -rf` with `rimraf` on the `clean` script
[x] Added `cross-conf-env` to `compile:browser` step, so `$npm_package_config_build_file` is interpreted correctly
- `version:write` and `version:changelog` may also benefit from `cross-conf-env`
=> Fixed broken npm install on Windows

src/quibble.browser.js
- looks like this was pointed to lib originally, but got changed in 45b73bf1
- this caused modules that referenced this ES6 version of the file in src to fail unless they were transpiling quibble.browser.js
=> replace quibble.browser.js with ES5 version

.circleci/config.yml, .travis.yml, README.md, package.json, script/run-examples
=> Merge Circle CI config to master

examples/jest-broken/package-lock.json, examples/jest-broken/package.json, examples/jest/package.json, examples/jest/support/helper.js, src/index.js, src/replace/jest-module.js, test/unit/index.test.js
This is not my favorite thing to do, but b/c quibble is stateful
and some extensions will need its absolutify() function (since
testdouble-jest and others are basically just meta test helpers)
that means they'll need the ability to call 
quibble.ignoreCallsToThisFile.
This probably will never be needed by end users but might come in handy.
¯\_(ツ)_/¯
I'd warn users to consider this private & undocumented, though unlikely to break
=> Export td.quibble

script/repl, src/matchers/builtin/contains.js, test/safe/matchers.test.js
Previously the comparison logic for traversable JS objects was separate
(presumably to avoid cycles, but possibly also because it was a
partial equality check, whereas the top-level contains() routine was a
case-by-case assessment of whether something contained something else.
This leads to confusing edge cases where something considered
"contained" when inside a {} property would not be considered contained
when passed to the top-level matcher. Whatever benefit this might have
conferred was surely more confusing than it was worth.
This only really required a change to one existing test-case, that is
when whatever is passed to contains() happens to deeply equal whatever
is actually passed, but that was never really a supported requirement,
so I'm wary of judging this a breaking change, …
=> Enhance contains for edge cases, make nesting behave consistently

README.md
Just a missing `h` in `loadsPurchases`
=> Fix method name typo in README example

src/reset.js, test/unit/reset.test.js
Pursuant to #377, this PR adds support for an `onReset` hook. It also adds a test spec for reset functionality as I noticed one was missing.
=> Add onReset hook.

index.d.ts, package-lock.json, package.json
Added imitation function to the exported types file for #395. After looking through, I think it's just imitate that was added in the public API doc. I'm not too familiar with the underlying code here, so feel free to nitpick away.
I also updated the minimum version for npm-run-all to 4.1.5 due to mystictea/npm-run-all#149 / dominictarr/event-stream#116 I can break out this section if desired, but included it as I needed to do this for `npm install` to succeed.
=> Add type information for imitation to the exported typings file

index.d.ts
continuing from #399 
@searls was right, the object function has all the necessary functionality built in. The only thing I had to tweak was this new type that allows for:
```javascript
td.object<IMyInterface>(); 
```
but even with the current code testdouble actually allowed for mocking based on an interface, but with a bit of redundancy:
```javascript
td.object<IMyInterface>("");
````
@wpannell you can use the second one already (with an argument of a string) for your training, with this merged in you will be able to remove the argument for a bit cleaner syntax.
=> allow for creating testdoubles using interface only

README.md
Also I find it amazing that this PR is also #404 
/cc @alexlafroscia who might have a new link to the docs
=> docs: Correct broken link to testdouble-qunit

package-lock.json, package.json, src/imitate/index.js, src/value/call-log.js, src/value/stubbing-register.js
As a follow-up to #367, this PR removes the `es6-map` dependency from `testdouble.js`.
=> Remove unnecessary dependency on es6-map.

docs/5-stubbing-results.md, docs/6-verifying-invocations.md, src/explain.js, src/store/calls.js, src/store/stubbings.js, src/wrap/lodash.js, test/safe/explain.test.js, test/safe/verify.test.js, test/safe/when.test.js
Fixes #375 
Fixes #416
Note that this will be a performance regression for anybody calling test doubles with large or hard to deep-clone arguments. Since that falls firmly in the category of "not how td.js is designed to be used", I'm going to put this out there and then see what hell it wreaks rather than aggressively benchmark now.
=> add cloneArgs option to td.when/td.verify

src/object.js, test/safe/object.test.js
cc @primarilysnark 
This PR addresses [Issue 370](https://github.com/testdouble/testdouble.js/issues/370).
Context: When `td.object` is called with an array of function names, it returns an array; my understanding of the issue is that `td.object` should always return an object.
From the original issue:
```
> td.object({ something() {} }).splice
undefined
> td.object(['something']).splice
[Function: splice]
```
Included Changes:
- Add an assertion to the `td.object` w/ array of function names test, to confirm that the resulting object is _not_ an array.
- Add a base value of `{}` to the accumulator in `createTestDoublesForFunctionNames`, to ensure that it responds with an object.
=> [Issue-370] - Update createTestDoublesForFunctionNames to return an object

index.d.ts
TypeScript declaration for `td.matchers.create()` has been added according to the API described at https://github.com/testdouble/testdouble.js/blob/master/docs/8-custom-matchers.md#tdmatcherscreate-api.
=> Missing TypeScript declaration for td.matchers.create() added

README.md, examples/node-ava/test/lib/instance-of-test.js, examples/node/test/lib/instance-of-test.js, examples/plain-html/test/math-problem-test.js, examples/webpack/test/math-problem-test.js, index.d.ts, src/index.js, src/index.mjs, src/instance.js, src/object.js, test/safe/instance.test.js, test/safe/object.test.js, test/safe/testdouble.test.js, test/safe/typescript-typings.test.ts, test/safe/verify.test.js, test/unit/index.test.js
=> Add td.instance()

docs/A-plugins.md
Adds `testdouble-qunit` to list of plugins that integrate Testdouble with populate test runners
=> docs: add `testdouble-qunit` to Plugins list

docs/7-replacing-dependencies.md
The example passed `node` to `NODE_OPTIONS` which is wrong and made it to not work.
=> fix NODE_OPTIONS example to specify the loader

docs/5-stubbing-results.md
Heya, 
Newcomer to TD so please, don't mock me 😏
On my journey through the docs I landed [here](https://github.com/testdouble/testdouble.js/blob/master/docs/5-stubbing-results.md#loosening-stubbings-with-argument-matchers) coming from [here](https://github.com/testdouble/testdouble.js#tdwhen-for-stubbing-responses) and found myself confused because the first example above had nothing to do with it. Over the course of making the proposed edit I realized that the original text "examples above" is correct, but it's like three examples (code blocks) ago, and not any of the example invocations in the code block above.
I think this change could help, and even if the reader was coming from the top of the doc, they're just getting a little bit of reinforcement. And we can both agree that …
=> Easier on readers when following links

docs/9-debugging.md
Because of the missing backtick, the wrong sections of text were being formatted as code.
**Before**
**After**
=> Fix Incorrect Formatting in Docs

docs/7-replacing-dependencies.md
This branch fixes a small typo in the replacing dependencies docs.
=> Fix Typo in Replacing Dependencies Docs

index.d.ts
Providing a namespace for the module as a whole allows to simplify defining a global instance of `td`. See [this comment](https://github.com/testdouble/testdouble.js/issues/441#issuecomment-851978147).
=> Provide module namespace

docs/A-plugins.md
A while back I simplified the `testdouble-qunit` repo to remove the monorepo structure (as the Ember-specific package that used to also live there became unnecessary). The original documentation link is no longer valid; this updates it to just point directly to the repo itself.
=> docs: fix link to `testdouble-qunit` plugin

index.d.ts, test/safe/typescript-typings.test.ts
This allows you to stub an async function with a sequence of promises that may either resolve or reject.
It will also not allow you to provide non-promise values when stubbing async functions (which is good)
closed #478
=> Add `thenReturn` to `PromiseStubber` type declaration

package.json
For a TypeScript project that has `moduleResolution: "nodenext"` set, TypeScript won't respect the existance of an `index.d.ts` when providing type definitions for a module.
Explicitly adding the `"types"` condition in the export definition, as supported by TypeScript 4.7 and later, resolves this problem.
***
I ran into the issue described above while migrating one of my projects to use TypeScript with native ESM. Applying this same fix through a `yarn` patch resolved the issue for my project; hopefully getting this fix upstream will avoid other people bumping into the same thing that I did!
=> Add `types` export condition

index.d.ts
Currently, as of the latest version 3.16.7: (#499, CC @asdftd @searls)
```ts
// `subscriptions` is `void`
const subscriptions = await td.replaceEsm(
'../../subscriptions.js',
);
```
Now:
```ts
// `subscriptions` is `{ [namedExport: string]: any; default?: any; }`
const subscriptions = await td.replaceEsm(
'../../subscriptions.js',
);
```
=> fix: replaceEsm typings

docs/7-replacing-dependencies.md
The API for `td.replaceEsm` differs a bit in argument interpretation compared to `td.replace` one, explain it and give documentation reference to `quibble.esm`.
I intentionally did not give details about the `default` possible value in `namedExportReplacements` because it requires a more recent version of quibble which has not been released yet.
=> add documentation for td.replaceEsm API

README.md, docs/1-installation.md, examples/babel/package-lock.json, examples/babel/test/helper.js, examples/jest-broken/package-lock.json, examples/jest/package-lock.json, examples/jest/support/helper.js, examples/node-ava/package-lock.json, examples/node-esm/package-lock.json, examples/node/package-lock.json, examples/node/test/helper.js, package-lock.json, package.json, script/repl, src/config.js, src/imitate/overwrite-children/is-fakeable.js, test/helper.js, test/safe/config.test.js, test/safe/constructor.test.js, test/safe/log.test.js, test/safe/object.test.js, test/support/tdify-plugin.js, test/unit/config.test.js, test/unit/imitate/create-imitation.test.js, test/unit/imitate/overwrite-children/is-fakeable.test.js
I ran into the same issue as #438 and #471 but the workarounds didn't work. Our stack is TypeScript + esbuild + Karma + mocha (and hopefully testdouble 😀 ). Our library is completely browser-based so we only want to test in real browsers.
These changes are largely the same as #472 but also upgrades the supported node engine as mentioned in https://github.com/testdouble/testdouble.js/issues/471#issuecomment-933481803 . [Node.js Release Schedule](https://github.com/nodejs/release#release-schedule)
=> Replace usage of global with globalThis for better browser support

src/index.mjs
I'm using testdouble as an ES module (with `import * from 'testdouble'`) and I wasn't able to use the `td.function()`, but only the `td.func()` alias.
It seems the `index.mjs` forgot to export the name `function`.
This patch fix it by adding an alias for `func` in the `index.mjs` file.
I didn't find where to add a test for this, I'll do it if you can give me some insights.
=> add missing function alias for ES module

index.d.ts
Hello there,
[In TypeScript](https://github.com/microsoft/TypeScript/blob/f64f40d20511d2d2a9eb4fcc1ad6750977be2d40/src/lib/es2015.promise.d.ts#L42), `Promise.reject` accepts a reason of type `any`. 
Since `thenReject` is a short-hand for `thenReturn(Promise.reject)`, the proposal here is to make `thenReject` accept a parameter of type `any`. The same applies for `throw` vs. `thenThrow`.
Ciao!
=> make `thenThrow` and `thenReject` accept values of `any` type

index.d.ts
I noticed this was missing in the type definitions.
=> feat(types): add "version" export to type declaration
